### ISSUE TITLE
Create a base for cv2

### ISSUE THREAD

**Issue by mohammed-shakir** [mohammed-shakir/Camera-Tracking-Using-UWB-Navigation#14]
Create a simple base code for the cv2 model that is consistent, and will work most of the time with no issues

**Comment by 1Ahm1** [comment]
import cv2

# Load an image
img = cv2.imread('image.jpg')

# Check if the image was successfully loaded
if img is None:
    print("Error: Could not load the image.")
    exit()

# Display the image
cv2.imshow('Image', img)

# Wait for a key event and save it in the 'key' variable
key = cv2.waitKey(0)

# Check if the 'q' key was pressed
if key == ord('q'):
    print("Exiting program.")

# Close all open windows
cv2.destroyAllWindows()

**Comment by 1Ahm1** [comment]
import cv2

# Create a VideoCapture object to access the camera
cap = cv2.VideoCapture(0)

# Check if the camera was successfully opened
if not cap.isOpened():
    print("Error: Could not open the camera.")
    exit()

# Define the ROI (Region of Interest)
roi = None

while True:
    # Read a frame from the camera
    ret, frame = cap.read()

    # Check if the frame was successfully read
    if not ret:
        print("Error: Could not read a frame from the camera.")
        break

    # If the ROI has not been defined
    if roi is None:
        # Display the frame and prompt the user to select the ROI
        r = cv2.selectROI(frame)
        roi = frame[int(r[1]):int(r[1]+r[3]), int(r[0]):int(r[0]+r[2])]
        continue

    # Convert the frame to grayscale
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Use template matching to detect the ROI in the frame
    res = cv2.matchTemplate(gray, roi, cv2.TM_CCOEFF_NORMED)
    _, max_val, _, max_loc = cv2.minMaxLoc(res)

    # Draw a rectangle around the detected ROI
    top_left = max_loc
    bottom_right = (top_left[0] + roi.shape[1], top_left[1] + roi.shape[0])
    cv2.rectangle(frame, top_left, bottom_right, (0, 255, 0), 2)

    # Display the frame with the rectangle
    cv2.imshow('Camera', frame)

    # Wait for a key event and save it in the 'key' variable
    key = cv2.waitKey(1)

    # Check if the 'q' key was pressed
    if key == ord('q'):
        print("Exiting program.")
        break

# Release the camera and close all open windows
cap.release()
cv2.destroyAllWindows()
