### ISSUE TITLE
Connect cv2 to the IP-cameras

### ISSUE THREAD

**Issue by mohammed-shakir** [mohammed-shakir/Camera-Tracking-Using-UWB-Navigation#20]
Find a way to connect cv2 to the IP-cameras. It is easy to open cv2 in a new instance on its own, but we need it to be working with the old code base and on the http://127.0.0.1:5000/ IP, so that it detects people using the old system.

**Comment by 1Ahm1** [comment]
import cv2

# URL of the IP camera
url = "http://127.0.0.1:5000/"

# Create a VideoCapture object
cap = cv2.VideoCapture(url)

# Check if the camera is opened
if not cap.isOpened():
    print("Error opening the camera")
    exit()

# Capture video frames
while True:
    # Read a frame
    ret, frame = cap.read()

    # Check if the frame is read successfully
    if not ret:
        print("Error reading the frame")
        break

    # Detect people in the frame
    # (your existing code for people detection)

    # Display the frame
    cv2.imshow("Frame", frame)

    # Break the loop if 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the VideoCapture object
cap.release()

# Close all windows
cv2.destroyAllWindows()
``

**Comment by MohamedDinawi** [comment]
We decided on connecting directly to the IP camera ip adress
